version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: weather_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weather_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis  # Important: doit correspondre au nom du service
      - REDIS_PORT=6379
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge